import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  primaryButton: {
    position: 'absolute',
    width: '83%',
    height: 59,
    left: 38,
    top: 490,
    backgroundColor: '#EE008F',
    borderRadius: 50,
  },
  primaryText: {
    position: 'absolute',
    width: 74.99,
    height: 24,
    left: 150,
    top: 16,
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 20,
    lineHeight: 24,
    color: '#FFFFFF',
  },
  secondaryButton: {
    position: 'absolute',
    width: '83%',
    height: 59,
    left: 38,
    top: 490,
    backgroundColor: '#1B0536',
    borderColor: '#FFFFFF',
    borderWidth: 2.5,
    borderRadius: 50,
  },
  secondaryText: {
    position: 'absolute',
    width: 74.99,
    height: 24,
    left: 150,
    top: 16,
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 20,
    lineHeight: 24,
    color: '#FFFFFF',
  },
});
